// reactjs/senior/reactjs-senior.jsx
import React, { useState } from "react";

const Highlighter = () => {
  const [sourceText, setSourceText] = useState("");
  const [searchTerm, setSearchTerm] = useState("");
  const [caseSensitive, setCaseSensitive] = useState(false);

  const handleSourceTextChange = (event) => {
    setSourceText(event.target.value);
  };

  const handleSearchTermChange = (event) => {
    setSearchTerm(event.target.value);
  };

  const handleCaseSensitiveChange = () => {
    setCaseSensitive(!caseSensitive);
  };

  const highlightText = (text) => {
    if (searchTerm === "") {
      return text;
    }

    const regexFlags = caseSensitive ? "g" : "gi";
    const regex = new RegExp(searchTerm, regexFlags);

    return text.replace(regex, (match) => `<mark>${match}</mark>`);
  };

  const highlightedText = highlightText(sourceText);

  return (
    <>
      <textarea
        data-testid="source-text"
        value={sourceText}
        onChange={handleSourceTextChange}
      />
      <br/>
      <input
        data-testid="search-term"
        value={searchTerm}
        onChange={handleSearchTermChange}
      />
      <br/>
      case sensitive ?
      <input
        type="checkbox"
        data-testid="case-sensitive"
        checked={caseSensitive}
        onChange={handleCaseSensitiveChange}
      />
      <div
        data-testid="result"
        dangerouslySetInnerHTML={{ __html: highlightedText }}
      ></div>
    </>
  );
};

export default Highlighter;

// solers-io/vuejs/senior/vue-senior.vue
<template>
    <div>
        <textarea data-testid="source-text" v-model="sourceText" @input="updateResult" />
        <br />
        <input data-testid="search-term" v-model="searchTerm" @input="updateResult" />
        <br />
        case sensitive ?
        <input type="checkbox" data-testid="case-sensitive" v-model="caseSensitive" @change="updateResult" />
        <div data-testid="result" v-html="highlightedText"></div>
    </div>
</template>
  
<script>
export default {
    data() {
        return {
            sourceText: "",
            searchTerm: "",
            caseSensitive: false,
        };
    },
    computed: {
        highlightedText() {
            return this.highlightText(this.sourceText);
        },
    },
    methods: {
        updateResult() {
            this.$nextTick(() => {
                const resultElement = this.$refs.result;
                if (resultElement) {
                    resultElement.innerHTML = this.highlightedText;
                }
            });
        },
        highlightText(text) {
            if (this.searchTerm === "") {
                return text;
            }

            const searchTermRegex = new RegExp(
                this.escapeRegExp(this.searchTerm),
                this.caseSensitive ? "g" : "gi"
            );
            return text.replace(searchTermRegex, (match) => `<mark>${match}</mark>`);
        },
        escapeRegExp(string) {
            return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        },
    },
};
</script>
